import {
  LucideActivity,
  LucideArrowRight,
  LucideArrowUp,
  LucideBookOpen,
  LucideBot,
  LucideBrain,
  LucideCalendarClock,
  LucideChartColumnBig,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleHelp,
  LucideClipboardList,
  LucideClock3,
  LucideCopy,
  LucideFlame,
  LucideGraduationCap,
  LucideHeartPulse,
  LucideLayoutDashboard,
  LucideLightbulb,
  LucideMenu,
  LucideMessageCircle,
  LucideMessagesSquare,
  LucideMoonStar,
  LucideNotebookPen,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePaperclip,
  LucidePenTool,
  LucidePlus,
  LucideRefreshCcw,
  LucideScanSearch,
  LucideSearch,
  LucideSend,
  LucideSettings2,
  LucideSparkles,
  LucideSquare,
  LucideStar,
  LucideSunMedium,
  LucideThumbsDown,
  LucideThumbsUp,
  LucideUserRound,
  LucideTrash2,
  LucideBarChart3,
  LucideFlaskConical,
  LucideLayers,
  LucideLogOut,
  LucideSettings,
  LucideUser,
  LucideWandSparkles,
  LucideCalendar,
  LucideFileText,
  LucideHistory,
  LucideZap,
  LucideBookmark,
  LucideImage,
  LucideCheckCircle2,
  LucideMail,
  LucideLock,
  LucideSquarePen,
  LucidePanelRightClose,
  LucideLibraryBig,
  LucideMoreHorizontal,
  LucideMic,
  LucideEye,
  LucideEyeOff,
  LucideCheck,
  LucideAlertCircle,
  LucideShieldCheck,
  LucideShare2
} from '@lucide/angular';

export const appIcons = {
  Activity: LucideActivity,
  ArrowUp: LucideArrowUp,
  ArrowRight: LucideArrowRight,
  BookOpen: LucideBookOpen,
  Bot: LucideBot,
  Brain: LucideBrain,
  CalendarClock: LucideCalendarClock,
  ChartColumnBig: LucideChartColumnBig,
  ChevronDown: LucideChevronDown,
  ChevronLeft: LucideChevronLeft,
  ChevronRight: LucideChevronRight,
  CircleHelp: LucideCircleHelp,
  ClipboardList: LucideClipboardList,
  Clock3: LucideClock3,
  Copy: LucideCopy,
  Flame: LucideFlame,
  GraduationCap: LucideGraduationCap,
  HeartPulse: LucideHeartPulse,
  LayoutDashboard: LucideLayoutDashboard,
  Lightbulb: LucideLightbulb,
  Menu: LucideMenu,
  MessageCircle: LucideMessageCircle,
  MessagesSquare: LucideMessagesSquare,
  MoonStar: LucideMoonStar,
  NotebookPen: LucideNotebookPen,
  PanelLeftClose: LucidePanelLeftClose,
  PanelLeftOpen: LucidePanelLeftOpen,
  Paperclip: LucidePaperclip,
  PenTool: LucidePenTool,
  Plus: LucidePlus,
  RefreshCcw: LucideRefreshCcw,
  ScanSearch: LucideScanSearch,
  Search: LucideSearch,
  Send: LucideSend,
  Settings2: LucideSettings2,
  Sparkles: LucideSparkles,
  Square: LucideSquare,
  Star: LucideStar,
  SunMedium: LucideSunMedium,
  ThumbsDown: LucideThumbsDown,
  ThumbsUp: LucideThumbsUp,
  Trash2: LucideTrash2,
  BarChart3: LucideBarChart3,
  FlaskConical: LucideFlaskConical,
  Layers: LucideLayers,
  LogOut: LucideLogOut,
  Settings: LucideSettings,
  User: LucideUser,
  UserRound: LucideUserRound,
  WandSparkles: LucideWandSparkles,
  Calendar: LucideCalendar,
  FileText: LucideFileText,
  History: LucideHistory,
  Zap: LucideZap,
  Bookmark: LucideBookmark,
  Image: LucideImage,
  CheckCircle2: LucideCheckCircle2,
  Mail: LucideMail,
  Lock: LucideLock,
  SquarePen: LucideSquarePen,
  PanelRightClose: LucidePanelRightClose,
  LibraryBig: LucideLibraryBig,
  MoreHorizontal: LucideMoreHorizontal,
  Mic: LucideMic,
  Eye: LucideEye,
  EyeOff: LucideEyeOff,
  Check: LucideCheck,
  AlertCircle: LucideAlertCircle,
  ShieldCheck: LucideShieldCheck,
  Share2: LucideShare2
};
